import { Auth, ThemeSupa } from '@supabase/auth-ui-react'
import { useSession, useSupabaseClient } from '@supabase/auth-helpers-react'
import { useRouter } from 'next/router'
import Head from 'next/head'

export default function Home() {
  const session   = useSession()
  const supabase  = useSupabaseClient()
  const router    = useRouter()
  if(session){router.push('/protected/dashboard')}

  return (
    <>
      <Head>
        <title>Train Me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen bg-gradient-to-b from-gray-100 to-blue-300">
        <div className="m-auto">
          <div>
            <h1 className="text-3xl mt-6 text-regalblue">Login</h1>
          </div>
          <div>
            <Auth 
              supabaseClient={supabase} 
              appearance={{ 
                  theme: ThemeSupa,
                  variables: {
                    default: {
                      colors: {
                        brand: 'red',
                        brandAccent: 'darkred',
                      },
                    },
                  },
                 }} 
             //providers={['google', 'facebook', 'twitter']}
              />
          </div>
        </div>
      </div>
    </>
  )
}
