import { Auth, ThemeSupa } from '@supabase/auth-ui-react'
import { useSession, useSupabaseClient } from '@supabase/auth-helpers-react'
import { useRouter } from 'next/router'
import Head from 'next/head'

export default function Home() {
  const session   = useSession()
  const supabase  = useSupabaseClient()
  const router    = useRouter()
  if(session){router.push('/protected/dashboard')}

  return (
    <>
      <Head>
        <title>Train Me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen">
        <div className="m-auto">
          <div className="flex-initial m-1.5">
            <h1 className="text-3xl mt-6 text-regalblue">Login</h1>
          </div>
          <div>
            <Auth supabaseClient={supabase} appearance={{ theme: ThemeSupa }} />
          </div>
        </div>
      </div>
    </>
  )
}
